version: "3.7"

services:
  app:
    build:
      context: .
      target: develop
    image: tikhoplav/partyphone:dev
    volumes:
      - ./src:/src
      - ./pkg:/go/pkg
    environment:
      - DB_URL=postgres://psql:psql@db/psql
    ports:
      - 80:80

  db:
    image: postgres:alpine
    volumes:
      - ./docker/db/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=psql
      - POSTGRES_USER=psql
      - POSTGRES_DB=psql